security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        Sio\SemiBundle\Entity\Participant : plaintext

    role_hierarchy:
        ROLE_GESTIONNAIRE:  [ROLE_PARTICIPANT]
        ROLE_ADMIN:         [ROLE_GESTIONNAIRE,ROLE_PARTICIPANT]
        ROLE_SUPER_ADMIN:   [ROLE_GESTIONNAIRE,ROLE_PARTICIPANT, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        main:
            entity: { class: Sio\SemiBundle\Entity\Participant, property: mail }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main_cle:
            pattern:  ^/$
            anonymous: true
        main_login:
            pattern:  ^/connexion
            anonymous: true
        main:
            pattern:  ^/gestion
            anonymous: false
            provider: main
            form_login:
                login_path: connect_user
                check_path: login_check
                always_use_default_target_path : true
                default_target_path: /gestion
                use_referer : true
            logout:
                path: logout
                target: /

        

    access_control:
        - { path: ^/gestion, roles: [ROLE_PARTICIPANT] }
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
