# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ANONYMOUS:     ROLE_ANONYMOUS
        ROLE_USER:          ROLE_USER
        ROLE_MANAGER:       [ROLE_USER, ROLE_MANAGER, ROLE_ALLOWED_TO_SWITCH]
        ROLE_ADMIN:         [ROLE_USER, ROLE_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        fos_userbundle:
            id: sio.user_provider.email # see UserBundle services

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        main:
            pattern:   ^/
            form_login:
                provider:  fos_userbundle
                csrf_provider: form.csrf_provider
                default_target_path: /redirect
            logout:    true                          
            anonymous: true

    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin, role: ROLE_ADMIN }
        - { path: ^/manager, role: ROLE_MANAGER }
        - { path: ^/user, role: ROLE_USER }