<?php

namespace Sio\SemiBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeminaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeminaireRepository extends EntityRepository
{
    public function existKey($cle){
        $q = $this->createQueryBuilder('SELECT s FROM Seminaire s WHERE cle = :key')
                ->setParameter('key', $cle)
                ->getQuery();
        if(!empty($q->getArrayResult())){
            return true;
        }else{
            return false;
        }
    }
}
